language: c

jobs:
 include:
  - os: linux
    dist: precise
    compiler: gcc
    before_script:
     - mkdir build
     - cd build
     - cmake .. -DCMAKE_BUILD_TYPE=Release
    script: make
  - os: linux
    dist: precise
    compiler: clang
    before_script:
     - mkdir build
     - cd build
     - cmake .. -DCMAKE_BUILD_TYPE=Release
    script: make

  - os: linux
    dist: trusty
    compiler: gcc
    before_script:
     - mkdir build
     - cd build
     - cmake .. -DCMAKE_BUILD_TYPE=Release
    script: make
  - os: linux
    dist: trusty
    compiler: clang
    before_script:
     - mkdir build
     - cd build
     - cmake .. -DCMAKE_BUILD_TYPE=Release
    script: make

  - os: linux
    dist: bionic
    compiler: gcc
    before_script:
     - mkdir build
     - cd build
     - cmake .. -DCMAKE_BUILD_TYPE=Release
    script: make
  - os: linux
    dist: bionic
    compiler: clang
    before_script:
     - mkdir build
     - cd build
     - cmake .. -DCMAKE_BUILD_TYPE=Release
    script: make

  - os: linux
    dist: xenial
    compiler: gcc
    before_script:
     - mkdir build
     - cd build
     - cmake .. -DCMAKE_BUILD_TYPE=Release
    script: make
  - os: linux
    dist: xenial
    compiler: clang
    before_script:
     - mkdir build
     - cd build
     - cmake .. -DCMAKE_BUILD_TYPE=Release
    script: make

  - os: osx
    osx_image: xcode9
    compiler: clang
    before_script:
     - mkdir build
     - cd build
     - cmake .. -DCMAKE_BUILD_TYPE=Release
    script: make

  - os: windows
    compiler:
     - gcc
     - clang
    before_script:
     - mkdir build
     - cd build
     - cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
    script: nmake