language: c

jobs:
 include:
  - os: linux
    dist: precise
    compiler:
     - gcc
     - clang
    before_script:
     - mkdir build
     - cd build
     - cmake ..
    script: make

  - os: linux
    dist: trusty
    compiler:
     - gcc
     - clang
    before_script:
     - mkdir build
     - cd build
     - cmake ..
    script: make

  - os: linux
    dist: bionic
    compiler:
     - gcc
     - clang
    before_script:
     - mkdir build
     - cd build
     - cmake ..
    script: make

  - os: linux
    dist: xenial
    compiler:
     - gcc
     - clang
    before_script:
     - mkdir build
     - cd build
     - cmake ..
    script: make

  - os: osx
    osx_image: xcode9
    compiler: clang
    before_script:
     - mkdir build
     - cd build
     - cmake ..
    script: make

  - os: windows
    compiler:
     - clang
     - gcc
    before_script:
     - mkdir build
     - cd build
     - cmake -G "NMake Makefiles"
    script: nmake